export const colors = {
  cynicalBlack: '#171717',
  cynicalBlack90: 'rgba(23, 23, 23, 0.9)',
  cynicalBlack00: 'rgba(23, 23, 23, 0)',
  voidBlack: '#0E0D0B',
  white0D: '#FFFFFF0D',
  codexGrey1A: '#9C9C9C1A',
  codexGrey: '#9C9C9C',
  white: '#FFFFFF',
  whiteWarm: '#F0E4DE',
  grey99: '#999999',
  tickGrey: '#383838',
  orangeRed: '#FF4500',
  orangePeel: '#FE6A01',
  fireOpal: '#FD3D07',
  peachGlow: '#FFB59A',
  orangeBtnStart: 'rgba(254, 72, 1, 0.9)',
  orangeBtnEnd: 'rgba(254, 104, 1, 0.9)',
  lacqueredLiquorice33: '#38383833',
  glassBorder: 'rgba(255, 255, 255, 0.12)',
  cardBorder: '#404040',
  titleAccentStart: '#FFB070',
  titleAccentMid: '#FF7A35',
  titleAccentEnd: '#FF4500',
  journalTitleStart: '#F5E9E2',
  journalTitleMid: '#FF8B5C',
  journalTitleEnd: '#FF5E3A',
  markerOrangeStart: '#E95029',
  markerOrangeMid: '#EC6A2E',
  markerOrangeEnd: '#FE7A30',
  progressOrangeStart: '#FF5620',
  progressOrangeMid: '#FF6B2B',
  progressOrangeEnd: '#FE7A30',
  pillBg: 'rgba(255, 255, 255, 0.07)',
  pillBorder: 'rgba(255, 255, 255, 0.16)',
  pillText: '#FFFFFF',
  promptFillTop: '#1A1A1A',
  promptFillMid: '#121212',
  promptFillBottom: '#0A0A0A',
  /** Rim — soft top highlight, muted visible bottom edge */
  promptBorderTop: 'rgba(255, 255, 255, 0.30)',
  promptBorderUpper: 'rgba(255, 255, 255, 0.14)',
  promptBorderLower: 'rgba(255, 255, 255, 0.08)',
  promptBorderBottom: 'rgba(255, 255, 255, 0.18)',
  inputBarBg: '#222222',
  inputBarBorder: 'rgba(255, 255, 255, 0.08)',
  inputBarRimTop: 'rgba(255, 255, 255, 0.20)',
  inputBarRimMid: 'rgba(255, 255, 255, 0.08)',
  inputBarRimBottom: 'rgba(255, 255, 255, 0.03)',
  bottomCurve: 'rgba(255, 255, 255, 0.22)',
  placeholder: '#A0A0A0',
  micOrange: '#FF5D0D',
  micOrangeStart: '#FF6B1A',
  micOrangeMid: '#FF4D00',
  micOrangeEnd: '#E63C00',
} as const

export const gradients = {
  titleFade: [colors.white, colors.grey99] as [string, string],
  markerTick: [
    colors.markerOrangeStart,
    colors.markerOrangeMid,
    colors.markerOrangeEnd,
  ] as [string, string, string],
  rulerFadeLeft: [
    colors.cynicalBlack,
    colors.cynicalBlack90,
    colors.cynicalBlack00,
  ] as [string, string, string],
  rulerFadeRight: [
    colors.cynicalBlack00,
    colors.cynicalBlack90,
    colors.cynicalBlack,
  ] as [string, string, string],
  progressSegment: [
    colors.progressOrangeStart,
    colors.progressOrangeMid,
    colors.progressOrangeEnd,
  ] as [string, string, string],
  iAmIn: [colors.white, colors.peachGlow, colors.fireOpal] as [
    string,
    string,
    string,
  ],
  commitDivider: [colors.codexGrey, colors.fireOpal] as [string, string],
  titleAccent: [
    colors.titleAccentStart,
    colors.titleAccentMid,
    colors.titleAccentEnd,
  ] as [string, string, string],
  /** Journal hero title — pale peach → coral, left → right */
  journalTitle: [
    colors.journalTitleStart,
    colors.journalTitleMid,
    colors.journalTitleEnd,
  ] as [string, string, string],
  primaryButton: [colors.orangePeel, colors.orangeRed] as [string, string],
  primaryButtonFill: [colors.orangeBtnStart, colors.orangeBtnEnd] as [
    string,
    string,
  ],
  /** Capsule fill — #1A1A1A → #0A0A0A */
  promptFill: [
    colors.promptFillTop,
    colors.promptFillMid,
    colors.promptFillBottom,
  ] as [string, string, string],
  /** Capsule rim — bright top + muted bottom, sides softer */
  promptBorder: [
    colors.promptBorderTop,
    colors.promptBorderUpper,
    colors.promptBorderLower,
    colors.promptBorderBottom,
  ] as [string, string, string, string],
  /** Input bar rim — subtle top highlight */
  inputBarBorder: [
    colors.inputBarRimTop,
    colors.inputBarRimMid,
    colors.inputBarRimBottom,
  ] as [string, string, string],
  /** Mic button — bright orange → deep red-orange */
  micButton: [
    colors.micOrangeStart,
    colors.micOrangeMid,
    colors.micOrangeEnd,
  ] as [string, string, string],
} as const
