export const Strings = {
  howLong: 'How Long?',
  setDurationSubtitle: 'Set the total challenge duration in days',
  setDuration: 'SET DURATION',
  workoutDays: 'Workout Days',
  restDays: 'Rest Days',
  days5: '5 Days',
  days90: '90 Days',
  quickCommitment: 'Quick Commitment',
  makeItOfficial: 'Make it official',
  promiseToYourself: 'This is a promise to yourself.',
  commitPrefix: 'I, ',
  userName: 'Siddanth Nair',
  commitSuffix: ', commit to:',
  commitPoint1: 'Show up for my workouts daily',
  commitPoint2: 'Staying consistent, even on the hard days',
  commitPoint3: 'Putting my health first',
  commitPoint4: 'Becoming the best version of my self',
  commitDisclaimer:
    'I understand that if I miss a workout, I will lose money and if I complete the challenge, ',
  earnItBack: 'I will earn it back.',
  iAmIn: 'I AM IN.',
  signatureDisclaimer: '*Your signature will not be recorded or stored',
  letsLockIt: "LET'S LOCK IT",
  tellMe: 'Tell me ',
  about: 'about',
  yourDay: 'your day, ',
  userFirstName: 'Pranav',
  promptChallenge: 'What challenged you the most today?',
  promptProud: 'What are you proud of today?',
  promptMind: "What's on your mind right now?",
  startTyping: 'Start typing or tap on the blob to speak...',
} as const
